import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialA1Sidebar: [{type: 'autogenerated', dirName: 'A1 Niveau'}],
  tutorialA2Sidebar: [{type: 'autogenerated', dirName: 'A2 Niveau'}],
  tutorialB1Sidebar: [{type: 'autogenerated', dirName: 'B1 Niveau'}],
  tutorialDuHocSidebar: [{type: 'autogenerated', dirName: 'Du Học'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
